name: build sulfur

on:
  push:
    branches: [ "build" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc nasm make python3

    - name: build profanOS disk
      run: |
        git clone https://github.com/elydre/profanOS.git
        cd profanOS
        make disk
        cd ..

    - name: build files
      run: |
        make linux_one_file1
        mv build/sulfur sulfur-onefile-linux-x86_64

        make linux
        mv build/sulfur sulfur-linux-x86_64

        cd build/
        zip -r ../libs-linux-x86_64.zip libs/
        cd ..

        python3 profan_build.py profanOS
        mv build/sulfur.elf sulfur-profanOS-i386.elf

    - name: Release to GitHub
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: sulfur latest
        automatic_release_tag: latest
        repo_token: "${{ secrets.GIT_TOKEN }}"
        prerelease: false
        files: |
          sulfur-onefile-linux-x86_64
          sulfur-linux-x86_64
          libs-linux-x86_64.zip
          sulfur-profanOS-i386.elf
